### ISSUE TITLE
Upgrading example to Android embedding v2

### ISSUE THREAD

**Issue by pspatel602** [iberatkaya/playify#4]
When I try to run the example app in VS code. It is not run dues to older version Android
embedding.

**Comment by iberatkaya** [comment]
Playify only supports iOS. I plan to add Android support in the future, but currently it is not supported on Android. Still the example should have run on Android even though it will not do anything, so I will check it out.

**Comment by fotiDim** [comment]
One question regarding Android support... will it be though Apple's MusicKit Android SDK?

**Comment by iberatkaya** [comment]
I think Apple's MusicKit Android SDK is for only playing Apple Music songs on Android. If so, I implemented Playify as a more generic music player plugin. On iOS, the only way to access and play songs from the users media library was through MediaPlayer. That is the reason MusicKit is used on iOS. I had not planned to make Playify a wrapper for Apple Music for Flutter, so MusicKit Android SDK will most likely not be used for Android. Feel free to suggest otherwise.

**Comment by fotiDim** [comment]
@iberatkaya I see. I don't think that there is any MusicKit Flutter project for Android though. Perhaps your work can be used as a starting point for a new package aimed exclusively at MusicKit for iOS/Android/Web. Do you mind if I fork it and start a new package?

**Comment by iberatkaya** [comment]
@fotiDim I also have not seen any MusicKit plugin for Android/Web. Yes, you can fork it and start a new package. I think that would be a great addition to Flutter!
